spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
